### ISSUE TITLE
Latest version breaks the library

### ISSUE THREAD

**Issue by purpleidea** [coreos/go-systemd#113]
```
~/.../gopath/src/github.com/coreos/go-systemd/dbus$ go test
# github.com/coreos/go-systemd/dbus
./dbus.go:67: undefined: dbus.BusObject
./dbus.go:71: undefined: dbus.BusObject
FAIL	github.com/coreos/go-systemd/dbus [build failed]
```

Not sure when it broke, but it broke.

**Comment by purpleidea** [comment]
(Either that, or I'm misunderstanding something about go dependencies, which is likely too!)

**Comment by jonboulle** [comment]
Is your godbus/dbus up to date?

**Comment by purpleidea** [comment]
I thought so, but I'm happy to run whatever commands you think are correct to fix this.
I ran it out of the gopath as shown.

**Comment by jonboulle** [comment]
Please try go get -u github.com/godbus/dbus

**Comment by purpleidea** [comment]
> Please try go get -u github.com/godbus/dbus

Strange, I'm a bit embarrassed that this has fixed the issue. Perhaps I've misunderstood something about where golang is storing it's code or this dependency mechanism.

Sorry for the noise, but any tips are appreciated.

**Comment by jonboulle** [comment]
Basically if you `go get` a package (so in this case `go get
github.com/coreos/go-systemd`), `go` will retrieve all the dependencies
automatically UNLESS they're already present... in which case, it won't try
to update them. So if you happen to have an older version of the dependent
library (i.e. github.com/godbus/dbus) in your `GOPATH`, you unfortunately
end up with this situation.

One way to try avoid this is just to always use the `-u` flag so that
dependencies will always be updated. For CoreOS projects we generally just
use an entirely self-contained GOPATH and/or vendor dependencies to avoid
this (see for example https://github.com/coreos/fleet/blob/master/build#L6)
