### ISSUE TITLE
Hide dependencies on systemd headers behind conditional compilation

### ISSUE THREAD

**Issue by charles-dyfis-net** [coreos/go-systemd#283]
There are a few reasons the dependency on systemd to compile sd-journal is unfortunate:

- Parts of go-systemd can legitimately be used (or at least tested) on platforms that can't run systemd at all.
- Pulling in systemd bits at compile time complicates the licensing status of this library. (Yes, the parts of systemd used here are LGPLed, but since *some* parts are GPLed, I can speak for there being at least one corporate bureaucracy that generates extra paperwork when compiling and/or linking against them).

Would a patch that made compilation of sdjournal conditional be welcome?

**Comment by lucab** [comment]
I think that none of those points are actual issues that need to be addressed.

This repository is already organized in multiple packages, so that packages that don't require systemd FFI are already pure Go modules. Consumers do import specific packages as required, not the umbrella repository.

The license in this repository covers its source code; when aggregated together with other pieces the resulting license for the aggregate needs to be evaluated case by case. Additionally, for the specific case of sd-journal, there is no direct linking involved in the final binary as the library is dlopen-ed at runtime.

**Comment by charles-dyfis-net** [comment]
Indeed -- directly being able to `go get github.com/coreos/go-systemd/unit` solves my issue. Apologies for the noise.
