### ISSUE TITLE
Can activation.Listener only be called once ?

### ISSUE THREAD

**Issue by liaojie** [coreos/go-systemd#286]
Hello, 
I have a foo.socket which have two ListenStream configuration, and they're in different modules of my codes. In the first module after calling activation.Listeners() I can get these two listeners. But calling it again in the second module later returns a empty slice. After removing it in the first module, just calling this function in the second module, I get the correct result.

So it seems that in a process the activation.Listeners() can be called only once ?

Thanks

**Comment by lucab** [comment]
> So it seems that in a process the activation.Listeners() can be called only once?

Yes, because it operates on global process state (file descriptors) and take ownership of them. It used to be possible to do what you are describing, but we discovered that it was actually racy due to behavior of the Go runtime. You can follow the full explanation and references at https://github.com/coreos/go-systemd/pull/276.

**Comment by liaojie** [comment]
Got it, Thanks for your reply.

**Comment by lucab** [comment]
@liaojie you're welcome. I am going to close this, feel free to ask if you have more doubts.
