### ISSUE TITLE
Retag v1 to v21 to be compatible with expected module versions

### ISSUE THREAD

**Issue by icholy** [coreos/go-systemd#346]
The module experience would be greatly improved if versions v1 to v21 were re-tagged with full semver versions.

So:
```
v1 -> v1.0.0
v2 -> v2.0.0
v3 -> v3.0.0
// etc ...
```
This would let the module proxy pick them up, and display them in https://pkg.go.dev/mod/github.com/coreos/go-systemd?tab=versions

**Comment by lucab** [comment]
Thanks for the report. There are more details about this in https://github.com/coreos/go-systemd/issues/321, but the short answer is the current status is correct.

The longer answer is that this library has been developed (and tagged) for a long time before gomod came to existence. All the releases up to `v21` were using other dependency manifests and are not directly compatible with gomod. This is because they lack versioned imports and mod/sum files, which did not exist at the time. The different tagging schema is just one of the observable symptoms, but the incompatibility is deeper than than.

The list in the module proxy is correct, only releases starting from `v22.0.0` can be used as a valid go module imports.
