### ISSUE TITLE
failed to read message field

### ISSUE THREAD

**Issue by shenxin** [coreos/go-systemd#380]
Hi, we have a in-house written tools to read journal log and write it to a log file, on some of the machines, it failed to run with the following error:
failed to read message field: 74
I think I know that it's due to some log entry from journald that was not correctly parsed/recognized by sdjournal module, this error seems coming from journal.go in sdjournal module, can anyone please help to identify on how to find out the log entry that cause this failure

**Comment by lucab** [comment]
You are using an ancient version of this library.  https://github.com/coreos/go-systemd/pull/308 was merged more than three years to provided better error messages for those cases.

Anyway it looks like you are getting a `-EBADMSG` from `sd_journal_enumerate_data`, which according to the manpage may be due to a corrupted journal.

I don't think this is a library bug, so I'm closing this. If you find otherwise, feel free to followup directly here.
