### ISSUE TITLE
Golang: syscall.WriteMsgUnix breaks large journal

### ISSUE THREAD

**Issue by philips** [coreos/go-systemd#5]
This is a tracking issue for the upstream Golang bug that keeps the large journal entry stuff from working right now. Large journal entries won't work until this is fixed upstream in Golang:

https://code.google.com/p/go/issues/detail?id=6476

**Comment by mildred** [comment]
Apparently this is going to be fixed in go 1.10 at worst : https://go-review.googlesource.com/c/go/+/45872

**Comment by mildred** [comment]
Is it possible to clarify which API are affected? Will using the `sdjournal` package, especially the functions on `sdjournal.Journal` can cause problems.

I am asking because I have an issue with journalbeat which uses go-systemd. Recently, logs got corrupted, and I was indeed having very large journal files that were being rotated by journald.

**Comment by lucab** [comment]
@mildred yes, I'm waiting for for 1.9 to rebase and then cherry-pick to `x/sys` as well. But I don't think this bug is related in any way to what you are seeing, it only affects clients trying to send large entries (send will fail).

**Comment by lucab** [comment]
Good news is that my [fix](https://go-review.googlesource.com/c/go/+/45872) is now released as part of Go 1.10. Bad news is that after backporting to `x/sys` I realized we can't really start using it right now.

I will wait for the next Go release (1.11) before starting to use it, thus closing this is ticket at that point. Until then, this still blocks https://github.com/coreos/go-systemd/pull/218#discussion_r105828158.
